//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libvirt.Header {
    
    
    public enum VirConnectCloseReason {
        
        VirConnectCloseReasonError = 0,
        
        VirConnectCloseReasonEof = 1,
        
        VirConnectCloseReasonKeepalive = 2,
        
        VirConnectCloseReasonClient = 3,
    }
    
    public enum VirTypedParameterType {
        
        VirTypedParamInt = 1,
        
        VirTypedParamUint = 2,
        
        VirTypedParamLlong = 3,
        
        VirTypedParamUllong = 4,
        
        VirTypedParamDouble = 5,
        
        VirTypedParamBoolean = 6,
        
        VirTypedParamString = 7,
    }
    
    [System.FlagsAttribute()]
    public enum VirTypedParameterFlags {
        
        VirTypedParamStringOkay = 4,
    }
    
    [System.FlagsAttribute()]
    public enum VirNodeSuspendTarget {
        
        VirNodeSuspendTargetMem = 0,
        
        VirNodeSuspendTargetDisk = 1,
        
        VirNodeSuspendTargetHybrid = 2,
    }
    
    public enum VirNodeGetCpustatsAllCpus {
        
        VirNodeCpuStatsAllCpus = -1,
    }
    
    public enum VirNodeGetMemoryStatsAllCells {
        
        VirNodeMemoryStatsAllCells = -1,
    }
    
    [System.FlagsAttribute()]
    public enum VirConnectFlags {
        
        VirConnectRo = 1,
        
        VirConnectNoAliases = 2,
    }
    
    public enum VirConnectCredentialType {
        
        VirCredUsername = 1,
        
        VirCredAuthname = 2,
        
        VirCredLanguage = 3,
        
        VirCredCnonce = 4,
        
        VirCredPassphrase = 5,
        
        VirCredEchoprompt = 6,
        
        VirCredNoechoprompt = 7,
        
        VirCredRealm = 8,
        
        VirCredExternal = 9,
    }
    
    public enum VirCpucompareResult {
        
        VirCpuCompareError = -1,
        
        VirCpuCompareIncompatible = 0,
        
        VirCpuCompareIdentical = 1,
        
        VirCpuCompareSuperset = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirConnectCompareCpuflags {
        
        VirConnectCompareCpuFailIncompatible = 1,
        
        VirConnectCompareCpuValidateXml = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirConnectBaselineCpuflags {
        
        VirConnectBaselineCpuExpandFeatures = 1,
        
        VirConnectBaselineCpuMigratable = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirNodeAllocPagesFlags {
        
        VirNodeAllocPagesAdd = 0,
        
        VirNodeAllocPagesSet = 1,
    }
    
    public enum VirDomainState {
        
        VirDomainNostate = 0,
        
        VirDomainRunning = 1,
        
        VirDomainBlocked = 2,
        
        VirDomainPaused = 3,
        
        VirDomainShutdown = 4,
        
        VirDomainShutoff = 5,
        
        VirDomainCrashed = 6,
        
        VirDomainPmsuspended = 7,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainNostateReason {
        
        VirDomainNostateUnknown = 0,
    }
    
    public enum VirDomainRunningReason {
        
        VirDomainRunningUnknown = 0,
        
        VirDomainRunningBooted = 1,
        
        VirDomainRunningMigrated = 2,
        
        VirDomainRunningRestored = 3,
        
        VirDomainRunningFromSnapshot = 4,
        
        VirDomainRunningUnpaused = 5,
        
        VirDomainRunningMigrationCanceled = 6,
        
        VirDomainRunningSaveCanceled = 7,
        
        VirDomainRunningWakeup = 8,
        
        VirDomainRunningCrashed = 9,
        
        VirDomainRunningPostcopy = 10,
        
        VirDomainRunningPostcopyFailed = 11,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainBlockedReason {
        
        VirDomainBlockedUnknown = 0,
    }
    
    public enum VirDomainPausedReason {
        
        VirDomainPausedUnknown = 0,
        
        VirDomainPausedUser = 1,
        
        VirDomainPausedMigration = 2,
        
        VirDomainPausedSave = 3,
        
        VirDomainPausedDump = 4,
        
        VirDomainPausedIoerror = 5,
        
        VirDomainPausedWatchdog = 6,
        
        VirDomainPausedFromSnapshot = 7,
        
        VirDomainPausedShuttingDown = 8,
        
        VirDomainPausedSnapshot = 9,
        
        VirDomainPausedCrashed = 10,
        
        VirDomainPausedStartingUp = 11,
        
        VirDomainPausedPostcopy = 12,
        
        VirDomainPausedPostcopyFailed = 13,
        
        VirDomainPausedApiError = 14,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainShutdownReason {
        
        VirDomainShutdownUnknown = 0,
        
        VirDomainShutdownUser = 1,
    }
    
    public enum VirDomainShutoffReason {
        
        VirDomainShutoffUnknown = 0,
        
        VirDomainShutoffShutdown = 1,
        
        VirDomainShutoffDestroyed = 2,
        
        VirDomainShutoffCrashed = 3,
        
        VirDomainShutoffMigrated = 4,
        
        VirDomainShutoffSaved = 5,
        
        VirDomainShutoffFailed = 6,
        
        VirDomainShutoffFromSnapshot = 7,
        
        VirDomainShutoffDaemon = 8,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainCrashedReason {
        
        VirDomainCrashedUnknown = 0,
        
        VirDomainCrashedPanicked = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainPmsuspendedReason {
        
        VirDomainPmsuspendedUnknown = 0,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainPmsuspendedDiskReason {
        
        VirDomainPmsuspendedDiskUnknown = 0,
    }
    
    public enum VirDomainControlState {
        
        VirDomainControlOk = 0,
        
        VirDomainControlJob = 1,
        
        VirDomainControlOccupied = 2,
        
        VirDomainControlError = 3,
    }
    
    public enum VirDomainControlErrorReason {
        
        VirDomainControlErrorReasonNone = 0,
        
        VirDomainControlErrorReasonUnknown = 1,
        
        VirDomainControlErrorReasonMonitor = 2,
        
        VirDomainControlErrorReasonInternal = 3,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainModificationImpact {
        
        VirDomainAffectCurrent = 0,
        
        VirDomainAffectLive = 1,
        
        VirDomainAffectConfig = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainCreateFlags {
        
        VirDomainNone = 0,
        
        VirDomainStartPaused = 1,
        
        VirDomainStartAutodestroy = 2,
        
        VirDomainStartBypassCache = 4,
        
        VirDomainStartForceBoot = 8,
        
        VirDomainStartValidate = 16,
        
        VirDomainStartResetNvram = 32,
    }
    
    public enum VirDomainMemoryStatTags {
        
        VirDomainMemoryStatSwapIn = 0,
        
        VirDomainMemoryStatSwapOut = 1,
        
        VirDomainMemoryStatMajorFault = 2,
        
        VirDomainMemoryStatMinorFault = 3,
        
        VirDomainMemoryStatUnused = 4,
        
        VirDomainMemoryStatAvailable = 5,
        
        VirDomainMemoryStatActualBalloon = 6,
        
        VirDomainMemoryStatRss = 7,
        
        VirDomainMemoryStatUsable = 8,
        
        VirDomainMemoryStatLastUpdate = 9,
        
        VirDomainMemoryStatDiskCaches = 10,
        
        VirDomainMemoryStatHugetlbPgalloc = 11,
        
        VirDomainMemoryStatHugetlbPgfail = 12,
        
        VirDomainMemoryStatNr = 13,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainCoreDumpFlags {
        
        VirDumpCrash = 1,
        
        VirDumpLive = 2,
        
        VirDumpBypassCache = 4,
        
        VirDumpReset = 8,
        
        VirDumpMemoryOnly = 16,
    }
    
    public enum VirDomainCoreDumpFormat {
        
        VirDomainCoreDumpFormatRaw = 0,
        
        VirDomainCoreDumpFormatKdumpZlib = 1,
        
        VirDomainCoreDumpFormatKdumpLzo = 2,
        
        VirDomainCoreDumpFormatKdumpSnappy = 3,
        
        VirDomainCoreDumpFormatWinDmp = 4,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainMigrateFlags {
        
        VirMigrateLive = 1,
        
        VirMigratePeer2Peer = 2,
        
        VirMigrateTunnelled = 4,
        
        VirMigratePersistDest = 8,
        
        VirMigrateUndefineSource = 16,
        
        VirMigratePaused = 32,
        
        VirMigrateNonSharedDisk = 64,
        
        VirMigrateNonSharedInc = 128,
        
        VirMigrateChangeProtection = 256,
        
        VirMigrateUnsafe = 512,
        
        VirMigrateOffline = 1024,
        
        VirMigrateCompressed = 2048,
        
        VirMigrateAbortOnError = 4096,
        
        VirMigrateAutoConverge = 8192,
        
        VirMigrateRdmaPinAll = 16384,
        
        VirMigratePostcopy = 32768,
        
        VirMigrateTls = 65536,
        
        VirMigrateParallel = 131072,
        
        VirMigrateNonSharedSynchronousWrites = 262144,
        
        VirMigratePostcopyResume = 524288,
        
        VirMigrateZerocopy = 1048576,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainMigrateMaxSpeedFlags {
        
        VirDomainMigrateMaxSpeedPostcopy = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainShutdownFlagValues {
        
        VirDomainShutdownDefault = 0,
        
        VirDomainShutdownAcpiPowerBtn = 1,
        
        VirDomainShutdownGuestAgent = 2,
        
        VirDomainShutdownInitctl = 4,
        
        VirDomainShutdownSignal = 8,
        
        VirDomainShutdownParavirt = 16,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainRebootFlagValues {
        
        VirDomainRebootDefault = 0,
        
        VirDomainRebootAcpiPowerBtn = 1,
        
        VirDomainRebootGuestAgent = 2,
        
        VirDomainRebootInitctl = 4,
        
        VirDomainRebootSignal = 8,
        
        VirDomainRebootParavirt = 16,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainDestroyFlagsValues {
        
        VirDomainDestroyDefault = 0,
        
        VirDomainDestroyGraceful = 1,
        
        VirDomainDestroyRemoveLogs = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainSaveRestoreFlags {
        
        VirDomainSaveBypassCache = 1,
        
        VirDomainSaveRunning = 2,
        
        VirDomainSavePaused = 4,
        
        VirDomainSaveResetNvram = 8,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainMemoryModFlags {
        
        VirDomainMemCurrent = 0,
        
        VirDomainMemLive = 1,
        
        VirDomainMemConfig = 2,
        
        VirDomainMemMaximum = 4,
    }
    
    public enum VirDomainNumatuneMemMode {
        
        VirDomainNumatuneMemStrict = 0,
        
        VirDomainNumatuneMemPreferred = 1,
        
        VirDomainNumatuneMemInterleave = 2,
        
        VirDomainNumatuneMemRestrictive = 3,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainGetHostnameFlags {
        
        VirDomainGetHostnameLease = 1,
        
        VirDomainGetHostnameAgent = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainMetadataType {
        
        VirDomainMetadataDescription = 0,
        
        VirDomainMetadataTitle = 1,
        
        VirDomainMetadataElement = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainXmlflags {
        
        VirDomainXmlSecure = 1,
        
        VirDomainXmlInactive = 2,
        
        VirDomainXmlUpdateCpu = 4,
        
        VirDomainXmlMigratable = 8,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainSaveImageXmlflags {
        
        VirDomainSaveImageXmlSecure = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainBlockResizeFlags {
        
        VirDomainBlockResizeBytes = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainMemoryFlags {
        
        VirMemoryVirtual = 1,
        
        VirMemoryPhysical = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainDefineFlags {
        
        VirDomainDefineValidate = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainUndefineFlagsValues {
        
        VirDomainUndefineManagedSave = 1,
        
        VirDomainUndefineSnapshotsMetadata = 2,
        
        VirDomainUndefineNvram = 4,
        
        VirDomainUndefineKeepNvram = 8,
        
        VirDomainUndefineCheckpointsMetadata = 16,
        
        VirDomainUndefineTpm = 32,
        
        VirDomainUndefineKeepTpm = 64,
    }
    
    [System.FlagsAttribute()]
    public enum VirConnectListAllDomainsFlags {
        
        VirConnectListDomainsActive = 1,
        
        VirConnectListDomainsInactive = 2,
        
        VirConnectListDomainsPersistent = 4,
        
        VirConnectListDomainsTransient = 8,
        
        VirConnectListDomainsRunning = 16,
        
        VirConnectListDomainsPaused = 32,
        
        VirConnectListDomainsShutoff = 64,
        
        VirConnectListDomainsOther = 128,
        
        VirConnectListDomainsManagedsave = 256,
        
        VirConnectListDomainsNoManagedsave = 512,
        
        VirConnectListDomainsAutostart = 1024,
        
        VirConnectListDomainsNoAutostart = 2048,
        
        VirConnectListDomainsHasSnapshot = 4096,
        
        VirConnectListDomainsNoSnapshot = 8192,
        
        VirConnectListDomainsHasCheckpoint = 16384,
        
        VirConnectListDomainsNoCheckpoint = 32768,
    }
    
    [System.FlagsAttribute()]
    public enum VirVcpuState {
        
        VirVcpuOffline = 0,
        
        VirVcpuRunning = 1,
        
        VirVcpuBlocked = 2,
    }
    
    public enum VirVcpuHostCpuState {
        
        VirVcpuInfoCpuOffline = -1,
        
        VirVcpuInfoCpuUnavailable = -2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainVcpuFlags {
        
        VirDomainVcpuCurrent = 0,
        
        VirDomainVcpuLive = 1,
        
        VirDomainVcpuConfig = 2,
        
        VirDomainVcpuMaximum = 4,
        
        VirDomainVcpuGuest = 8,
        
        VirDomainVcpuHotpluggable = 16,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainDeviceModifyFlags {
        
        VirDomainDeviceModifyCurrent = 0,
        
        VirDomainDeviceModifyLive = 1,
        
        VirDomainDeviceModifyConfig = 2,
        
        VirDomainDeviceModifyForce = 4,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainStatsTypes {
        
        VirDomainStatsState = 1,
        
        VirDomainStatsCpuTotal = 2,
        
        VirDomainStatsBalloon = 4,
        
        VirDomainStatsVcpu = 8,
        
        VirDomainStatsInterface = 16,
        
        VirDomainStatsBlock = 32,
        
        VirDomainStatsPerf = 64,
        
        VirDomainStatsIothread = 128,
        
        VirDomainStatsMemory = 256,
        
        VirDomainStatsDirtyrate = 512,
        
        VirDomainStatsVm = 1024,
    }
    
    [System.FlagsAttribute()]
    public enum VirConnectGetAllDomainStatsFlags {
        
        VirConnectGetAllDomainsStatsActive = 1,
        
        VirConnectGetAllDomainsStatsInactive = 2,
        
        VirConnectGetAllDomainsStatsPersistent = 4,
        
        VirConnectGetAllDomainsStatsTransient = 8,
        
        VirConnectGetAllDomainsStatsRunning = 16,
        
        VirConnectGetAllDomainsStatsPaused = 32,
        
        VirConnectGetAllDomainsStatsShutoff = 64,
        
        VirConnectGetAllDomainsStatsOther = 128,
        
        VirConnectGetAllDomainsStatsNowait = 536870912,
        
        VirConnectGetAllDomainsStatsBacking = 1073741824,
        
        VirConnectGetAllDomainsStatsEnforceStats = -2147483648,
    }
    
    public enum VirDomainBlockJobType {
        
        VirDomainBlockJobTypeUnknown = 0,
        
        VirDomainBlockJobTypePull = 1,
        
        VirDomainBlockJobTypeCopy = 2,
        
        VirDomainBlockJobTypeCommit = 3,
        
        VirDomainBlockJobTypeActiveCommit = 4,
        
        VirDomainBlockJobTypeBackup = 5,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainBlockJobAbortFlags {
        
        VirDomainBlockJobAbortAsync = 1,
        
        VirDomainBlockJobAbortPivot = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainBlockJobInfoFlags {
        
        VirDomainBlockJobInfoBandwidthBytes = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainBlockJobSetSpeedFlags {
        
        VirDomainBlockJobSpeedBandwidthBytes = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainBlockPullFlags {
        
        VirDomainBlockPullBandwidthBytes = 64,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainBlockRebaseFlags {
        
        VirDomainBlockRebaseShallow = 1,
        
        VirDomainBlockRebaseReuseExt = 2,
        
        VirDomainBlockRebaseCopyRaw = 4,
        
        VirDomainBlockRebaseCopy = 8,
        
        VirDomainBlockRebaseRelative = 16,
        
        VirDomainBlockRebaseCopyDev = 32,
        
        VirDomainBlockRebaseBandwidthBytes = 64,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainBlockCopyFlags {
        
        VirDomainBlockCopyShallow = 1,
        
        VirDomainBlockCopyReuseExt = 2,
        
        VirDomainBlockCopyTransientJob = 4,
        
        VirDomainBlockCopySynchronousWrites = 8,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainBlockCommitFlags {
        
        VirDomainBlockCommitShallow = 1,
        
        VirDomainBlockCommitDelete = 2,
        
        VirDomainBlockCommitActive = 4,
        
        VirDomainBlockCommitRelative = 8,
        
        VirDomainBlockCommitBandwidthBytes = 16,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainDiskErrorCode {
        
        VirDomainDiskErrorNone = 0,
        
        VirDomainDiskErrorUnspec = 1,
        
        VirDomainDiskErrorNoSpace = 2,
    }
    
    public enum VirKeycodeSet {
        
        VirKeycodeSetLinux = 0,
        
        VirKeycodeSetXt = 1,
        
        VirKeycodeSetAtset1 = 2,
        
        VirKeycodeSetAtset2 = 3,
        
        VirKeycodeSetAtset3 = 4,
        
        VirKeycodeSetOsx = 5,
        
        VirKeycodeSetXtKbd = 6,
        
        VirKeycodeSetUsb = 7,
        
        VirKeycodeSetWin32 = 8,
        
        VirKeycodeSetQnum = 9,
    }
    
    public enum VirDomainProcessSignal {
        
        VirDomainProcessSignalNop = 0,
        
        VirDomainProcessSignalHup = 1,
        
        VirDomainProcessSignalInt = 2,
        
        VirDomainProcessSignalQuit = 3,
        
        VirDomainProcessSignalIll = 4,
        
        VirDomainProcessSignalTrap = 5,
        
        VirDomainProcessSignalAbrt = 6,
        
        VirDomainProcessSignalBus = 7,
        
        VirDomainProcessSignalFpe = 8,
        
        VirDomainProcessSignalKill = 9,
        
        VirDomainProcessSignalUsr1 = 10,
        
        VirDomainProcessSignalSegv = 11,
        
        VirDomainProcessSignalUsr2 = 12,
        
        VirDomainProcessSignalPipe = 13,
        
        VirDomainProcessSignalAlrm = 14,
        
        VirDomainProcessSignalTerm = 15,
        
        VirDomainProcessSignalStkflt = 16,
        
        VirDomainProcessSignalChld = 17,
        
        VirDomainProcessSignalCont = 18,
        
        VirDomainProcessSignalStop = 19,
        
        VirDomainProcessSignalTstp = 20,
        
        VirDomainProcessSignalTtin = 21,
        
        VirDomainProcessSignalTtou = 22,
        
        VirDomainProcessSignalUrg = 23,
        
        VirDomainProcessSignalXcpu = 24,
        
        VirDomainProcessSignalXfsz = 25,
        
        VirDomainProcessSignalVtalrm = 26,
        
        VirDomainProcessSignalProf = 27,
        
        VirDomainProcessSignalWinch = 28,
        
        VirDomainProcessSignalPoll = 29,
        
        VirDomainProcessSignalPwr = 30,
        
        VirDomainProcessSignalSys = 31,
        
        VirDomainProcessSignalRt0 = 32,
        
        VirDomainProcessSignalRt1 = 33,
        
        VirDomainProcessSignalRt2 = 34,
        
        VirDomainProcessSignalRt3 = 35,
        
        VirDomainProcessSignalRt4 = 36,
        
        VirDomainProcessSignalRt5 = 37,
        
        VirDomainProcessSignalRt6 = 38,
        
        VirDomainProcessSignalRt7 = 39,
        
        VirDomainProcessSignalRt8 = 40,
        
        VirDomainProcessSignalRt9 = 41,
        
        VirDomainProcessSignalRt10 = 42,
        
        VirDomainProcessSignalRt11 = 43,
        
        VirDomainProcessSignalRt12 = 44,
        
        VirDomainProcessSignalRt13 = 45,
        
        VirDomainProcessSignalRt14 = 46,
        
        VirDomainProcessSignalRt15 = 47,
        
        VirDomainProcessSignalRt16 = 48,
        
        VirDomainProcessSignalRt17 = 49,
        
        VirDomainProcessSignalRt18 = 50,
        
        VirDomainProcessSignalRt19 = 51,
        
        VirDomainProcessSignalRt20 = 52,
        
        VirDomainProcessSignalRt21 = 53,
        
        VirDomainProcessSignalRt22 = 54,
        
        VirDomainProcessSignalRt23 = 55,
        
        VirDomainProcessSignalRt24 = 56,
        
        VirDomainProcessSignalRt25 = 57,
        
        VirDomainProcessSignalRt26 = 58,
        
        VirDomainProcessSignalRt27 = 59,
        
        VirDomainProcessSignalRt28 = 60,
        
        VirDomainProcessSignalRt29 = 61,
        
        VirDomainProcessSignalRt30 = 62,
        
        VirDomainProcessSignalRt31 = 63,
        
        VirDomainProcessSignalRt32 = 64,
    }
    
    public enum VirDomainEventType {
        
        VirDomainEventDefined = 0,
        
        VirDomainEventUndefined = 1,
        
        VirDomainEventStarted = 2,
        
        VirDomainEventSuspended = 3,
        
        VirDomainEventResumed = 4,
        
        VirDomainEventStopped = 5,
        
        VirDomainEventShutdown = 6,
        
        VirDomainEventPmsuspended = 7,
        
        VirDomainEventCrashed = 8,
    }
    
    public enum VirDomainEventDefinedDetailType {
        
        VirDomainEventDefinedAdded = 0,
        
        VirDomainEventDefinedUpdated = 1,
        
        VirDomainEventDefinedRenamed = 2,
        
        VirDomainEventDefinedFromSnapshot = 3,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainEventUndefinedDetailType {
        
        VirDomainEventUndefinedRemoved = 0,
        
        VirDomainEventUndefinedRenamed = 1,
    }
    
    public enum VirDomainEventStartedDetailType {
        
        VirDomainEventStartedBooted = 0,
        
        VirDomainEventStartedMigrated = 1,
        
        VirDomainEventStartedRestored = 2,
        
        VirDomainEventStartedFromSnapshot = 3,
        
        VirDomainEventStartedWakeup = 4,
    }
    
    public enum VirDomainEventSuspendedDetailType {
        
        VirDomainEventSuspendedPaused = 0,
        
        VirDomainEventSuspendedMigrated = 1,
        
        VirDomainEventSuspendedIoerror = 2,
        
        VirDomainEventSuspendedWatchdog = 3,
        
        VirDomainEventSuspendedRestored = 4,
        
        VirDomainEventSuspendedFromSnapshot = 5,
        
        VirDomainEventSuspendedApiError = 6,
        
        VirDomainEventSuspendedPostcopy = 7,
        
        VirDomainEventSuspendedPostcopyFailed = 8,
    }
    
    public enum VirDomainEventResumedDetailType {
        
        VirDomainEventResumedUnpaused = 0,
        
        VirDomainEventResumedMigrated = 1,
        
        VirDomainEventResumedFromSnapshot = 2,
        
        VirDomainEventResumedPostcopy = 3,
        
        VirDomainEventResumedPostcopyFailed = 4,
    }
    
    public enum VirDomainEventStoppedDetailType {
        
        VirDomainEventStoppedShutdown = 0,
        
        VirDomainEventStoppedDestroyed = 1,
        
        VirDomainEventStoppedCrashed = 2,
        
        VirDomainEventStoppedMigrated = 3,
        
        VirDomainEventStoppedSaved = 4,
        
        VirDomainEventStoppedFailed = 5,
        
        VirDomainEventStoppedFromSnapshot = 6,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainEventShutdownDetailType {
        
        VirDomainEventShutdownFinished = 0,
        
        VirDomainEventShutdownGuest = 1,
        
        VirDomainEventShutdownHost = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainEventPmsuspendedDetailType {
        
        VirDomainEventPmsuspendedMemory = 0,
        
        VirDomainEventPmsuspendedDisk = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainEventCrashedDetailType {
        
        VirDomainEventCrashedPanicked = 0,
        
        VirDomainEventCrashedCrashloaded = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainMemoryFailureRecipientType {
        
        VirDomainEventMemoryFailureRecipientHypervisor = 0,
        
        VirDomainEventMemoryFailureRecipientGuest = 1,
    }
    
    public enum VirDomainMemoryFailureActionType {
        
        VirDomainEventMemoryFailureActionIgnore = 0,
        
        VirDomainEventMemoryFailureActionInject = 1,
        
        VirDomainEventMemoryFailureActionFatal = 2,
        
        VirDomainEventMemoryFailureActionReset = 3,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainMemoryFailureFlags {
        
        VirDomainMemoryFailureActionRequired = 1,
        
        VirDomainMemoryFailureRecursive = 2,
    }
    
    public enum VirDomainJobType {
        
        VirDomainJobNone = 0,
        
        VirDomainJobBounded = 1,
        
        VirDomainJobUnbounded = 2,
        
        VirDomainJobCompleted = 3,
        
        VirDomainJobFailed = 4,
        
        VirDomainJobCancelled = 5,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainGetJobStatsFlags {
        
        VirDomainJobStatsCompleted = 1,
        
        VirDomainJobStatsKeepCompleted = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainAbortJobFlagsValues {
        
        VirDomainAbortJobPostcopy = 1,
    }
    
    public enum VirDomainJobOperation {
        
        VirDomainJobOperationUnknown = 0,
        
        VirDomainJobOperationStart = 1,
        
        VirDomainJobOperationSave = 2,
        
        VirDomainJobOperationRestore = 3,
        
        VirDomainJobOperationMigrationIn = 4,
        
        VirDomainJobOperationMigrationOut = 5,
        
        VirDomainJobOperationSnapshot = 6,
        
        VirDomainJobOperationSnapshotRevert = 7,
        
        VirDomainJobOperationDump = 8,
        
        VirDomainJobOperationBackup = 9,
        
        VirDomainJobOperationSnapshotDelete = 10,
    }
    
    public enum VirDomainEventWatchdogAction {
        
        VirDomainEventWatchdogNone = 0,
        
        VirDomainEventWatchdogPause = 1,
        
        VirDomainEventWatchdogReset = 2,
        
        VirDomainEventWatchdogPoweroff = 3,
        
        VirDomainEventWatchdogShutdown = 4,
        
        VirDomainEventWatchdogDebug = 5,
        
        VirDomainEventWatchdogInjectnmi = 6,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainEventIoerrorAction {
        
        VirDomainEventIoErrorNone = 0,
        
        VirDomainEventIoErrorPause = 1,
        
        VirDomainEventIoErrorReport = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainEventGraphicsPhase {
        
        VirDomainEventGraphicsConnect = 0,
        
        VirDomainEventGraphicsInitialize = 1,
        
        VirDomainEventGraphicsDisconnect = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainEventGraphicsAddressType {
        
        VirDomainEventGraphicsAddressIpv4 = 0,
        
        VirDomainEventGraphicsAddressIpv6 = 1,
        
        VirDomainEventGraphicsAddressUnix = 2,
    }
    
    public enum VirConnectDomainEventBlockJobStatus {
        
        VirDomainBlockJobCompleted = 0,
        
        VirDomainBlockJobFailed = 1,
        
        VirDomainBlockJobCanceled = 2,
        
        VirDomainBlockJobReady = 3,
    }
    
    [System.FlagsAttribute()]
    public enum VirConnectDomainEventDiskChangeReason {
        
        VirDomainEventDiskChangeMissingOnStart = 0,
        
        VirDomainEventDiskDropMissingOnStart = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainEventTrayChangeReason {
        
        VirDomainEventTrayChangeOpen = 0,
        
        VirDomainEventTrayChangeClose = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirConnectDomainEventAgentLifecycleState {
        
        VirConnectDomainEventAgentLifecycleStateConnected = 1,
        
        VirConnectDomainEventAgentLifecycleStateDisconnected = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirConnectDomainEventAgentLifecycleReason {
        
        VirConnectDomainEventAgentLifecycleReasonUnknown = 0,
        
        VirConnectDomainEventAgentLifecycleReasonDomainStarted = 1,
        
        VirConnectDomainEventAgentLifecycleReasonChannel = 2,
    }
    
    public enum VirDomainEventId {
        
        VirDomainEventIdLifecycle = 0,
        
        VirDomainEventIdReboot = 1,
        
        VirDomainEventIdRtcChange = 2,
        
        VirDomainEventIdWatchdog = 3,
        
        VirDomainEventIdIoError = 4,
        
        VirDomainEventIdGraphics = 5,
        
        VirDomainEventIdIoErrorReason = 6,
        
        VirDomainEventIdControlError = 7,
        
        VirDomainEventIdBlockJob = 8,
        
        VirDomainEventIdDiskChange = 9,
        
        VirDomainEventIdTrayChange = 10,
        
        VirDomainEventIdPmwakeup = 11,
        
        VirDomainEventIdPmsuspend = 12,
        
        VirDomainEventIdBalloonChange = 13,
        
        VirDomainEventIdPmsuspendDisk = 14,
        
        VirDomainEventIdDeviceRemoved = 15,
        
        VirDomainEventIdBlockJob2 = 16,
        
        VirDomainEventIdTunable = 17,
        
        VirDomainEventIdAgentLifecycle = 18,
        
        VirDomainEventIdDeviceAdded = 19,
        
        VirDomainEventIdMigrationIteration = 20,
        
        VirDomainEventIdJobCompleted = 21,
        
        VirDomainEventIdDeviceRemovalFailed = 22,
        
        VirDomainEventIdMetadataChange = 23,
        
        VirDomainEventIdBlockThreshold = 24,
        
        VirDomainEventIdMemoryFailure = 25,
        
        VirDomainEventIdMemoryDeviceSizeChange = 26,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainConsoleFlags {
        
        VirDomainConsoleForce = 1,
        
        VirDomainConsoleSafe = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainChannelFlags {
        
        VirDomainChannelForce = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainOpenGraphicsFlags {
        
        VirDomainOpenGraphicsSkipauth = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainSetTimeFlags {
        
        VirDomainTimeSync = 1,
    }
    
    public enum VirSchedParameterType {
        
        VirDomainSchedFieldInt = 1,
        
        VirDomainSchedFieldUint = 2,
        
        VirDomainSchedFieldLlong = 3,
        
        VirDomainSchedFieldUllong = 4,
        
        VirDomainSchedFieldDouble = 5,
        
        VirDomainSchedFieldBoolean = 6,
    }
    
    public enum VirBlkioParameterType {
        
        VirDomainBlkioParamInt = 1,
        
        VirDomainBlkioParamUint = 2,
        
        VirDomainBlkioParamLlong = 3,
        
        VirDomainBlkioParamUllong = 4,
        
        VirDomainBlkioParamDouble = 5,
        
        VirDomainBlkioParamBoolean = 6,
    }
    
    public enum VirMemoryParameterType {
        
        VirDomainMemoryParamInt = 1,
        
        VirDomainMemoryParamUint = 2,
        
        VirDomainMemoryParamLlong = 3,
        
        VirDomainMemoryParamUllong = 4,
        
        VirDomainMemoryParamDouble = 5,
        
        VirDomainMemoryParamBoolean = 6,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainInterfaceAddressesSource {
        
        VirDomainInterfaceAddressesSrcLease = 0,
        
        VirDomainInterfaceAddressesSrcAgent = 1,
        
        VirDomainInterfaceAddressesSrcArp = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainSetUserPasswordFlags {
        
        VirDomainPasswordEncrypted = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainLifecycle {
        
        VirDomainLifecyclePoweroff = 0,
        
        VirDomainLifecycleReboot = 1,
        
        VirDomainLifecycleCrash = 2,
    }
    
    public enum VirDomainLifecycleAction {
        
        VirDomainLifecycleActionDestroy = 0,
        
        VirDomainLifecycleActionRestart = 1,
        
        VirDomainLifecycleActionRestartRename = 2,
        
        VirDomainLifecycleActionPreserve = 3,
        
        VirDomainLifecycleActionCoredumpDestroy = 4,
        
        VirDomainLifecycleActionCoredumpRestart = 5,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainGuestInfoTypes {
        
        VirDomainGuestInfoUsers = 1,
        
        VirDomainGuestInfoOs = 2,
        
        VirDomainGuestInfoTimezone = 4,
        
        VirDomainGuestInfoHostname = 8,
        
        VirDomainGuestInfoFilesystem = 16,
        
        VirDomainGuestInfoDisks = 32,
        
        VirDomainGuestInfoInterfaces = 64,
    }
    
    public enum VirDomainAgentResponseTimeoutValues {
        
        VirDomainAgentResponseTimeoutBlock = -2,
        
        VirDomainAgentResponseTimeoutDefault = -1,
        
        VirDomainAgentResponseTimeoutNowait = 0,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainBackupBeginFlags {
        
        VirDomainBackupBeginReuseExternal = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainAuthorizedSshkeysSetFlags {
        
        VirDomainAuthorizedSshKeysSetAppend = 1,
        
        VirDomainAuthorizedSshKeysSetRemove = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainMessageType {
        
        VirDomainMessageDeprecation = 1,
        
        VirDomainMessageTainting = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainDirtyRateStatus {
        
        VirDomainDirtyrateUnstarted = 0,
        
        VirDomainDirtyrateMeasuring = 1,
        
        VirDomainDirtyrateMeasured = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainDirtyRateCalcFlags {
        
        VirDomainDirtyrateModePageSampling = 0,
        
        VirDomainDirtyrateModeDirtyBitmap = 1,
        
        VirDomainDirtyrateModeDirtyRing = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainFdassociateFlags {
        
        VirDomainFdAssociateSeclabelRestore = 1,
        
        VirDomainFdAssociateSeclabelWritable = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainCheckpointCreateFlags {
        
        VirDomainCheckpointCreateRedefine = 1,
        
        VirDomainCheckpointCreateQuiesce = 2,
        
        VirDomainCheckpointCreateRedefineValidate = 4,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainCheckpointXmlflags {
        
        VirDomainCheckpointXmlSecure = 1,
        
        VirDomainCheckpointXmlNoDomain = 2,
        
        VirDomainCheckpointXmlSize = 4,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainCheckpointListFlags {
        
        VirDomainCheckpointListRoots = 1,
        
        VirDomainCheckpointListDescendants = 1,
        
        VirDomainCheckpointListTopological = 2,
        
        VirDomainCheckpointListLeaves = 4,
        
        VirDomainCheckpointListNoLeaves = 8,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainCheckpointDeleteFlags {
        
        VirDomainCheckpointDeleteChildren = 1,
        
        VirDomainCheckpointDeleteMetadataOnly = 2,
        
        VirDomainCheckpointDeleteChildrenOnly = 4,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainSnapshotCreateFlags {
        
        VirDomainSnapshotCreateRedefine = 1,
        
        VirDomainSnapshotCreateCurrent = 2,
        
        VirDomainSnapshotCreateNoMetadata = 4,
        
        VirDomainSnapshotCreateHalt = 8,
        
        VirDomainSnapshotCreateDiskOnly = 16,
        
        VirDomainSnapshotCreateReuseExt = 32,
        
        VirDomainSnapshotCreateQuiesce = 64,
        
        VirDomainSnapshotCreateAtomic = 128,
        
        VirDomainSnapshotCreateLive = 256,
        
        VirDomainSnapshotCreateValidate = 512,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainSnapshotXmlflags {
        
        VirDomainSnapshotXmlSecure = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainSnapshotListFlags {
        
        VirDomainSnapshotListRoots = 1,
        
        VirDomainSnapshotListDescendants = 1,
        
        VirDomainSnapshotListLeaves = 4,
        
        VirDomainSnapshotListNoLeaves = 8,
        
        VirDomainSnapshotListMetadata = 2,
        
        VirDomainSnapshotListNoMetadata = 16,
        
        VirDomainSnapshotListInactive = 32,
        
        VirDomainSnapshotListActive = 64,
        
        VirDomainSnapshotListDiskOnly = 128,
        
        VirDomainSnapshotListInternal = 256,
        
        VirDomainSnapshotListExternal = 512,
        
        VirDomainSnapshotListTopological = 1024,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainSnapshotRevertFlags {
        
        VirDomainSnapshotRevertRunning = 1,
        
        VirDomainSnapshotRevertPaused = 2,
        
        VirDomainSnapshotRevertForce = 4,
        
        VirDomainSnapshotRevertResetNvram = 8,
    }
    
    [System.FlagsAttribute()]
    public enum VirDomainSnapshotDeleteFlags {
        
        VirDomainSnapshotDeleteChildren = 1,
        
        VirDomainSnapshotDeleteMetadataOnly = 2,
        
        VirDomainSnapshotDeleteChildrenOnly = 4,
    }
    
    [System.FlagsAttribute()]
    public enum VirEventHandleType {
        
        VirEventHandleReadable = 1,
        
        VirEventHandleWritable = 2,
        
        VirEventHandleError = 4,
        
        VirEventHandleHangup = 8,
    }
    
    [System.FlagsAttribute()]
    public enum VirConnectListAllInterfacesFlags {
        
        VirConnectListInterfacesInactive = 1,
        
        VirConnectListInterfacesActive = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirInterfaceXmlflags {
        
        VirInterfaceXmlInactive = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirInterfaceDefineFlags {
        
        VirInterfaceDefineValidate = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirNetworkXmlflags {
        
        VirNetworkXmlInactive = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirConnectListAllNetworksFlags {
        
        VirConnectListNetworksInactive = 1,
        
        VirConnectListNetworksActive = 2,
        
        VirConnectListNetworksPersistent = 4,
        
        VirConnectListNetworksTransient = 8,
        
        VirConnectListNetworksAutostart = 16,
        
        VirConnectListNetworksNoAutostart = 32,
    }
    
    [System.FlagsAttribute()]
    public enum VirNetworkCreateFlags {
        
        VirNetworkCreateValidate = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirNetworkDefineFlags {
        
        VirNetworkDefineValidate = 1,
    }
    
    public enum VirNetworkUpdateCommand {
        
        VirNetworkUpdateCommandNone = 0,
        
        VirNetworkUpdateCommandModify = 1,
        
        VirNetworkUpdateCommandDelete = 2,
        
        VirNetworkUpdateCommandAddLast = 3,
        
        VirNetworkUpdateCommandAddFirst = 4,
    }
    
    public enum VirNetworkUpdateSection {
        
        VirNetworkSectionNone = 0,
        
        VirNetworkSectionBridge = 1,
        
        VirNetworkSectionDomain = 2,
        
        VirNetworkSectionIp = 3,
        
        VirNetworkSectionIpDhcpHost = 4,
        
        VirNetworkSectionIpDhcpRange = 5,
        
        VirNetworkSectionForward = 6,
        
        VirNetworkSectionForwardInterface = 7,
        
        VirNetworkSectionForwardPf = 8,
        
        VirNetworkSectionPortgroup = 9,
        
        VirNetworkSectionDnsHost = 10,
        
        VirNetworkSectionDnsTxt = 11,
        
        VirNetworkSectionDnsSrv = 12,
    }
    
    [System.FlagsAttribute()]
    public enum VirNetworkUpdateFlags {
        
        VirNetworkUpdateAffectCurrent = 0,
        
        VirNetworkUpdateAffectLive = 1,
        
        VirNetworkUpdateAffectConfig = 2,
    }
    
    public enum VirNetworkEventLifecycleType {
        
        VirNetworkEventDefined = 0,
        
        VirNetworkEventUndefined = 1,
        
        VirNetworkEventStarted = 2,
        
        VirNetworkEventStopped = 3,
    }
    
    [System.FlagsAttribute()]
    public enum VirNetworkEventId {
        
        VirNetworkEventIdLifecycle = 0,
    }
    
    [System.FlagsAttribute()]
    public enum VirIpaddrType {
        
        VirIpAddrTypeIpv4 = 0,
        
        VirIpAddrTypeIpv6 = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirNetworkPortCreateFlags {
        
        VirNetworkPortCreateReclaim = 1,
        
        VirNetworkPortCreateValidate = 2,
    }
    
    [System.FlagsAttribute()]
    public enum VirConnectListAllNodeDeviceFlags {
        
        VirConnectListNodeDevicesCapSystem = 1,
        
        VirConnectListNodeDevicesCapPciDev = 2,
        
        VirConnectListNodeDevicesCapUsbDev = 4,
        
        VirConnectListNodeDevicesCapUsbInterface = 8,
        
        VirConnectListNodeDevicesCapNet = 16,
        
        VirConnectListNodeDevicesCapScsiHost = 32,
        
        VirConnectListNodeDevicesCapScsiTarget = 64,
        
        VirConnectListNodeDevicesCapScsi = 128,
        
        VirConnectListNodeDevicesCapStorage = 256,
        
        VirConnectListNodeDevicesCapFcHost = 512,
        
        VirConnectListNodeDevicesCapVports = 1024,
        
        VirConnectListNodeDevicesCapScsiGeneric = 2048,
        
        VirConnectListNodeDevicesCapDrm = 4096,
        
        VirConnectListNodeDevicesCapMdevTypes = 8192,
        
        VirConnectListNodeDevicesCapMdev = 16384,
        
        VirConnectListNodeDevicesCapCcwDev = 32768,
        
        VirConnectListNodeDevicesCapCssDev = 65536,
        
        VirConnectListNodeDevicesCapVdpa = 131072,
        
        VirConnectListNodeDevicesCapApCard = 262144,
        
        VirConnectListNodeDevicesCapApQueue = 524288,
        
        VirConnectListNodeDevicesCapApMatrix = 1048576,
        
        VirConnectListNodeDevicesCapVpd = 2097152,
        
        VirConnectListNodeDevicesInactive = 1073741824,
        
        VirConnectListNodeDevicesActive = -2147483648,
    }
    
    [System.FlagsAttribute()]
    public enum VirNodeDeviceCreateXmlflags {
        
        VirNodeDeviceCreateXmlValidate = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirNodeDeviceDefineXmlflags {
        
        VirNodeDeviceDefineXmlValidate = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirNodeDeviceEventId {
        
        VirNodeDeviceEventIdLifecycle = 0,
        
        VirNodeDeviceEventIdUpdate = 1,
    }
    
    public enum VirNodeDeviceEventLifecycleType {
        
        VirNodeDeviceEventCreated = 0,
        
        VirNodeDeviceEventDeleted = 1,
        
        VirNodeDeviceEventDefined = 2,
        
        VirNodeDeviceEventUndefined = 3,
    }
    
    [System.FlagsAttribute()]
    public enum VirNwfilterDefineFlags {
        
        VirNwfilterDefineValidate = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirNwfilterBindingCreateFlags {
        
        VirNwfilterBindingCreateValidate = 1,
    }
    
    public enum VirSecretUsageType {
        
        VirSecretUsageTypeNone = 0,
        
        VirSecretUsageTypeVolume = 1,
        
        VirSecretUsageTypeCeph = 2,
        
        VirSecretUsageTypeIscsi = 3,
        
        VirSecretUsageTypeTls = 4,
        
        VirSecretUsageTypeVtpm = 5,
    }
    
    [System.FlagsAttribute()]
    public enum VirConnectListAllSecretsFlags {
        
        VirConnectListSecretsEphemeral = 1,
        
        VirConnectListSecretsNoEphemeral = 2,
        
        VirConnectListSecretsPrivate = 4,
        
        VirConnectListSecretsNoPrivate = 8,
    }
    
    [System.FlagsAttribute()]
    public enum VirSecretDefineFlags {
        
        VirSecretDefineValidate = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirSecretEventId {
        
        VirSecretEventIdLifecycle = 0,
        
        VirSecretEventIdValueChanged = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirSecretEventLifecycleType {
        
        VirSecretEventDefined = 0,
        
        VirSecretEventUndefined = 1,
    }
    
    public enum VirStoragePoolState {
        
        VirStoragePoolInactive = 0,
        
        VirStoragePoolBuilding = 1,
        
        VirStoragePoolRunning = 2,
        
        VirStoragePoolDegraded = 3,
        
        VirStoragePoolInaccessible = 4,
    }
    
    [System.FlagsAttribute()]
    public enum VirStoragePoolBuildFlags {
        
        VirStoragePoolBuildNew = 0,
        
        VirStoragePoolBuildRepair = 1,
        
        VirStoragePoolBuildResize = 2,
        
        VirStoragePoolBuildNoOverwrite = 4,
        
        VirStoragePoolBuildOverwrite = 8,
    }
    
    [System.FlagsAttribute()]
    public enum VirStoragePoolDeleteFlags {
        
        VirStoragePoolDeleteNormal = 0,
        
        VirStoragePoolDeleteZeroed = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirStoragePoolCreateFlags {
        
        VirStoragePoolCreateNormal = 0,
        
        VirStoragePoolCreateWithBuild = 1,
        
        VirStoragePoolCreateWithBuildOverwrite = 2,
        
        VirStoragePoolCreateWithBuildNoOverwrite = 4,
    }
    
    public enum VirStorageVolType {
        
        VirStorageVolFile = 0,
        
        VirStorageVolBlock = 1,
        
        VirStorageVolDir = 2,
        
        VirStorageVolNetwork = 3,
        
        VirStorageVolNetdir = 4,
        
        VirStorageVolPloop = 5,
    }
    
    [System.FlagsAttribute()]
    public enum VirStorageVolDeleteFlags {
        
        VirStorageVolDeleteNormal = 0,
        
        VirStorageVolDeleteZeroed = 1,
        
        VirStorageVolDeleteWithSnapshots = 2,
    }
    
    public enum VirStorageVolWipeAlgorithm {
        
        VirStorageVolWipeAlgZero = 0,
        
        VirStorageVolWipeAlgNnsa = 1,
        
        VirStorageVolWipeAlgDod = 2,
        
        VirStorageVolWipeAlgBsi = 3,
        
        VirStorageVolWipeAlgGutmann = 4,
        
        VirStorageVolWipeAlgSchneier = 5,
        
        VirStorageVolWipeAlgPfitzner7 = 6,
        
        VirStorageVolWipeAlgPfitzner33 = 7,
        
        VirStorageVolWipeAlgRandom = 8,
        
        VirStorageVolWipeAlgTrim = 9,
    }
    
    [System.FlagsAttribute()]
    public enum VirStorageVolInfoFlags {
        
        VirStorageVolUseAllocation = 0,
        
        VirStorageVolGetPhysical = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirStorageXmlflags {
        
        VirStorageXmlInactive = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirConnectListAllStoragePoolsFlags {
        
        VirConnectListStoragePoolsInactive = 1,
        
        VirConnectListStoragePoolsActive = 2,
        
        VirConnectListStoragePoolsPersistent = 4,
        
        VirConnectListStoragePoolsTransient = 8,
        
        VirConnectListStoragePoolsAutostart = 16,
        
        VirConnectListStoragePoolsNoAutostart = 32,
        
        VirConnectListStoragePoolsDir = 64,
        
        VirConnectListStoragePoolsFs = 128,
        
        VirConnectListStoragePoolsNetfs = 256,
        
        VirConnectListStoragePoolsLogical = 512,
        
        VirConnectListStoragePoolsDisk = 1024,
        
        VirConnectListStoragePoolsIscsi = 2048,
        
        VirConnectListStoragePoolsScsi = 4096,
        
        VirConnectListStoragePoolsMpath = 8192,
        
        VirConnectListStoragePoolsRbd = 16384,
        
        VirConnectListStoragePoolsSheepdog = 32768,
        
        VirConnectListStoragePoolsGluster = 65536,
        
        VirConnectListStoragePoolsZfs = 131072,
        
        VirConnectListStoragePoolsVstorage = 262144,
        
        VirConnectListStoragePoolsIscsiDirect = 524288,
    }
    
    [System.FlagsAttribute()]
    public enum VirStoragePoolDefineFlags {
        
        VirStoragePoolDefineValidate = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirStorageVolCreateFlags {
        
        VirStorageVolCreatePreallocMetadata = 1,
        
        VirStorageVolCreateReflink = 2,
        
        VirStorageVolCreateValidate = 4,
    }
    
    [System.FlagsAttribute()]
    public enum VirStorageVolDownloadFlags {
        
        VirStorageVolDownloadSparseStream = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirStorageVolUploadFlags {
        
        VirStorageVolUploadSparseStream = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirStorageVolResizeFlags {
        
        VirStorageVolResizeAllocate = 1,
        
        VirStorageVolResizeDelta = 2,
        
        VirStorageVolResizeShrink = 4,
    }
    
    [System.FlagsAttribute()]
    public enum VirStoragePoolEventId {
        
        VirStoragePoolEventIdLifecycle = 0,
        
        VirStoragePoolEventIdRefresh = 1,
    }
    
    public enum VirStoragePoolEventLifecycleType {
        
        VirStoragePoolEventDefined = 0,
        
        VirStoragePoolEventUndefined = 1,
        
        VirStoragePoolEventStarted = 2,
        
        VirStoragePoolEventStopped = 3,
        
        VirStoragePoolEventCreated = 4,
        
        VirStoragePoolEventDeleted = 5,
    }
    
    [System.FlagsAttribute()]
    public enum VirStreamFlags {
        
        VirStreamNonblock = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirStreamRecvFlagsValues {
        
        VirStreamRecvStopAtHole = 1,
    }
    
    [System.FlagsAttribute()]
    public enum VirStreamEventType {
        
        VirStreamEventReadable = 1,
        
        VirStreamEventWritable = 2,
        
        VirStreamEventError = 4,
        
        VirStreamEventHangup = 8,
    }
}
